### ISSUE TITLE
Check_Chromedriver can't handle 64-bit Windows with 64-bit Chrome

### ISSUE THREAD

**Issue by DavidJLambert** [cuzai/Check_Chromedriver#3]
I'm running Check_Chromedriver on 64-bit Windows, and getting this stack trace:

```
You do not have Chrome browser.
chromebrowser_ver : None
Traceback (most recent call last):
  File "C:/Coding/PyCharm/projects/selenium/wyzant.py", line 25, in <module>
    from Check_Chromedriver import Check_Chromedriver
  File "C:\Coding\Python\PyVirtualEnvs\selenium\lib\site-packages\Check_Chromedriver\Check_Chromedriver.py", line 79, in <module>
    browser_ver_code = deal_reg.reg_version_code(browser_ver)
  File "C:\Coding\Python\PyVirtualEnvs\selenium\lib\site-packages\Check_Chromedriver\libs\deal_reg.py", line 23, in reg_version_code
    p = m.search(ver)
TypeError: expected string or bytes-like object
```

I have  64-bit Windows with 64-bit Chrome in C:/Program Files/Google/Chrome/Application, and the code in Check_Chromedriver.py, lines 39-42, assumes that if
`platform.architecture()[0] == "64bit"`
then
`ver_path = "C:/Program Files (x86)/Google/Chrome/Application"`
But I do not have even have a "C:/Program Files (x86)/Google/Chrome/Application" directory, since I have 64-bit Chrome.
I recommend ignoring `platform.architecture()[0]` and checking for the existence of chrome.exe in C:/Program Files (x86)/Google/Chrome/Application and C:/Program Files/Google/Chrome/Application.

**Comment by DavidJLambert** [comment]
I created a new version of `check_browser_ver` on my computer:
```
def check_browser_ver():
    try:
        if platform.architecture()[0] == "64bit":
            ver_path = "C:/Program Files (x86)/Google/Chrome/Application"
            if not os.path.exists(ver_path):
                ver_path = "C:/Program Files/Google/Chrome/Application"
                if not os.path.exists(ver_path):
                    raise Exception
        else:
            ver_path = "C:/Program Files/Google/Chrome/Application"
        for i in os.listdir(ver_path):
            if deal_reg.is_version(i):
                return i
    except Exception:
        print("You do not have Chrome browser.")
```
This fixes the problem.
